config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      post :confirm
    end
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  mount_uploader :picture, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  mount_uploader :icon, ImageUploader
  has_many :posts
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
  end
  
  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path, notice: "#{favorite.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_path, notice: "#{favorite.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  def new
    @post = Post.new
  end

  def edit
    unless current_user.id == @post.user_id
      redirect_to posts_path, notice: "権限がありません！"
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        PostMailer.post_mail(@post).deliver
        redirect_to posts_path, notice: "作成しました！"
      else
        render :new
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "更新しました！" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

  def destroy
    unless current_user.id == @post.user_id
      redirect_to posts_path, notice: "権限がありません！"
    else
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "削除しました！" }
        format.json { head :no_content }
      end
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:picture, :picture_cache, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: %i[ show edit update destroy ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
    unless current_user.id == @user.id
      redirect_to user_path(id: @user.id), notice: "権限がありません！"
    else
      @user = User.find(params[:id])
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(id: @user.id), notice: "編集しました！"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:icon, :name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1 class="title">お気に入り一覧</h1>
<div>
  <% @favorites.each do |favorite| %>
  <ul>
    <li><%= image_tag favorite.post.user.icon.url if favorite.post.user.icon && favorite.post.user.icon.url %></li>
    <li><%= favorite.post.user.name %></li>
    <li><%= image_tag favorite.post.picture.url if favorite.post.picture && favorite.post.picture.url %></li>
    <li><%= favorite.post.content %></li>
  </ul>
  <% end %>
</div>
<div><%= link_to "ホームへ", posts_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSharedApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if logged_in? %>
        <div class="status">ようこそ <%= current_user.name %> さん</div>
        <%= link_to "プロフィール", user_path(current_user.id), class:"link" %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete, class:"link" %>
      <% else %>
        <div class="status">ログインしてください</div>
        <%= link_to "アカウント作成", new_user_path, class:"link" %>
        <%= link_to "ログイン", new_session_path, class:"link" %>
      <% end %>
    </header>
    <div class="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form_area">
<%= form_with(model: post, local: true, url: choose_new_or_edit ) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :写真 %>
    <%= form.file_field :picture, class: "select" %>
  </div>

  <div class="field">
    <%= form.label :内容 %>
    <%= form.text_area :content, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit "投稿する", class: "btn" %>
    <%= link_to 'ホームへ', posts_path, class: "back" %>
  </div>
<% end %>
</div>

app/views/posts/confirm.html.erb
<h1>以下の内容で、投稿する。</h1>
<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <%= image_tag @post.picture.url, class: "picture" if @post.picture && @post.picture.url %>
  <%= form.hidden_field :picture_cache %>
  <%= form.hidden_field :content, class:"sentence" %>
  <p><%= @post.content %></p>
  <%= form.submit "登録する", class: "btn" %>
<% end %>
<%= form_with(model:@post, url:new_post_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :picture_cache %>
  <%= form.hidden_field :content, class:"sentence" %>
  <%= form.submit "戻る", name: 'back', class: "option" %>
<% end %>

app/views/posts/edit.html.erb
<h1>編集</h1>

<%= render 'form', post: @post %>

<%= link_to '詳細画面に戻る', @post, class: "option_btn" %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ホーム</h1>

<%= link_to '投稿する', new_post_path, class: "btn" %>

<div class="container-fluid">
  <ul class="row">
    <% @posts.each do |post| %>
      <li class="col-md-6 col-lg-4">
      <div class="chunk">
        <div class="user">
          <%= image_tag post.user.icon.url, class: "icon" if post.user.icon && post.user.icon.url %>
          <%= post.user.name %>
        </div>
        <div class="post">
          <%= image_tag post.picture.url, class: "picture" if post.picture && post.picture.url %>
          <p class="sentence"><%= post.content %></p>
        </div>
        <div class="option">
          <%= link_to '詳細', post, class: "option_btn" %>
          <% if post.user_id == current_user.id %>
            <%= link_to '編集', edit_post_path(post), data: { confirm: '本当に編集していいですか？' }, class: "option_btn" %>
            <%= link_to '削除', post, method: :delete, data: { confirm: '本当に削除していいですか？' }, class: "option_btn" %>
          <% end %>
        </div>
      </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<h1>新規作成</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<p><%= image_tag @post.user.icon.url, class: "icon" if @post.user.icon && @post.user.icon.url %></p>
<p><%= @post.user.name %></p>
<p><%= image_tag @post.picture.url, class: "picture" if @post.picture && @post.picture.url %></p>
<p><%= @post.content %></p>

<% unless @post.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<% if @post.user_id == current_user.id %>
  <%= link_to '編集', edit_post_path(@post), data: { confirm: '本当に編集していいですか？' }, class: "option_btn" %>
  <%= link_to '削除', @post, method: :delete, data: { confirm: '本当に削除していいですか？' }, class: "option_btn" %>
<% end %>
<%= link_to 'ホームへ', posts_path, class: "back" %>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <div class="field">
    <%= image_tag @user.icon.url, class: "picture" if @user.icon && @user.icon.url %>
    <%= f.label :アイコン %>
    <%= f.file_field :icon, class: "select" %>
  </div>
  <div class="field">
    <%= f.label :名前 %>
    <%= f.text_field :name, class: "input" %>
  </div>
  <div class="field">
    <%= f.label :メールアドレス %>
    <%= f.email_field :email, class: "input" %>
  </div>
  <div class="field">
    <%= f.label :パスワード %>
    <%= f.password_field :password, class: "input" %>
  </div>
  <div class="field">
    <%= f.label :確認用パスワード %>
    <%= f.password_field :password_confirmation, class: "input" %>
  </div>
  <div class="actions">
    <%= f.submit "プロフィールを更新", class: "btn" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>新しくアカウントを作成</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <div class="field">
    <%= image_tag f.icon.url, class: "picture" if @user.icon && @user.icon.url %>
    <%= f.label :icon %>
    <%= f.file_field :icon, class: "select" %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, class: "input" %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: "input" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "input" %>
  </div>
  <div class="actions">
    <%= f.submit "Create my account", class: "btn" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %> のページ</h1>
<p><%= image_tag @user.icon.url, class: "picture" if @user.icon && @user.icon.url %></p>
<p>メールアドレス: <%= @user.email %></p>
<%= link_to "お気に入り一覧", favorites_path, class: "back" %>
<%= link_to "ホームへ", posts_path, class:"btn" %>
<% if @user.id == current_user.id %>
  <%= link_to "プロフィール編集", edit_user_path(id: @user.id), class: "back" %>
<% end %>